apiVersion: v1
kind: Namespace
metadata:
  name: default-imagepullsecrets

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-imagepullsecrets
  namespace: default-imagepullsecrets
spec:
  dnsNames:
  - default-imagepullsecrets.default-imagepullsecrets.svc
  - default-imagepullsecrets.default-imagepullsecrets.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: default-imagepullsecrets-cert

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default-imagepullsecrets
spec:
  selfSigned: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: default-imagepullsecrets
  name: default-imagepullsecrets
  namespace: default-imagepullsecrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-imagepullsecrets
  template:
    metadata:
      labels:
        app: default-imagepullsecrets
    spec:
      containers:
      - args:
        - --cert-file=/cert/tls.crt
        - --key-file=/cert/tls.key
        - --image-pull-secrets=${DEFAULT_IMAGEPULLSECRETS}
        image: gjkim42/default-imagepullsecrets:${VERSION}
        name: default-imagepullsecrets
        volumeMounts:
        - mountPath: /cert
          name: cert
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: default-imagepullsecrets-cert

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: default-imagepullsecrets
  name: default-imagepullsecrets
  namespace: default-imagepullsecrets
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: default-imagepullsecrets
  type: NodePort
