apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: default-imagepullsecrets/default-imagepullsecrets
  name: default-imagepullsecrets
webhooks:
- name: default-imagepullsecrets.admisstion-controller.gjkim42
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      name: default-imagepullsecrets
      namespace: default-imagepullsecrets
      path: /webhook
  admissionReviewVersions:
  - v1
  - v1beta1
  sideEffects: None
  timeoutSeconds: 5
