name: Continuous integration
on:
  push:
    tags:
    - v*
    branches:
    - main
    - release-*
  pull_request:

env:
  GO_VERSION: '1.17'

concurrency:
  group: ci
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v2
    - uses: gjkim42/verify-go@v1

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v2
    - run: make build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v2
    - run: make test

  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make image

  test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set VERSION and deploy the test image
      run: |
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo VERSION ${VERSION}
        make image VERSION=${VERSION}
        docker login -u gjkim42 -p "${DOCKER_SECRET}"
        make push VERSION=${VERSION}
      env:
        DOCKER_SECRET: ${{ secrets.GJKIM42_DOCKER_PASSWORD }}
        VERSION: "test-e2e"

    - uses: helm/kind-action@v1.2.0

    - name: Install cert-manager
      run: |
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/${CERTMANAGER_VERSION}/cert-manager.yaml
        kubectl rollout status -n cert-manager deployment cert-manager-webhook
      env:
        CERTMANAGER_VERSION: "v1.7.2"

    - name: Set DEFAULT_IMAGEPULLSECRETS and deploy default-imagepullsecrets
      run: |
        echo "DEFAULT_IMAGEPULLSECRETS=${DEFAULT_IMAGEPULLSECRETS}" >> $GITHUB_ENV
        envsubst < default-imagepullsecrets.yaml | kubectl apply -f -
        kubectl rollout status -n default-imagepullsecrets deployment default-imagepullsecrets
        kubectl apply -f mutating-webhook-configuration.yaml
      env:
        DEFAULT_IMAGEPULLSECRETS: "mysecret0,my-secret1"

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: e2e test
      run: |
        go install github.com/onsi/ginkgo/v2/ginkgo@latest
        ginkgo ./test/e2e -- \
          --kubeconfig=${HOME}/.kube/config \
          --image-pull-secrets=${DEFAULT_IMAGEPULLSECRETS}
